
== FHIR Profilversionen
Das E-Rezept hat eine link:https://github.com/gematik/api-erp/blob/master/docs/erp_fhirversion.adoc[Versionierung der FHIR Profile]. Das bedeutet, dass mit der Zeit unterschiedliche _"Profil Konfigurationen"_ aktiv sind. Um diesem Umstand gerecht zu werden, können E-Rezept FHIR Ressourcen mit unterschiedlichen Profilversionen generiert und validiert werden.

Das Modul `erp-fhir` hat die folgende Konfiguration für die verfügbaren Profile:

[source,yaml]
----
include::../../erp-fhir/src/main/resources/parsers.yaml[]
----

=== Validierung
Für die Validierung von E-Rezept FHIR Ressourcen bedarf es keiner gesonderten Konfiguration. Die Version des Profiles ist in der Regel in der Ressource selbst enthalten. Sollte die Ressource keine Versionsangabe enthalten, wird für die Validierung standardmäßig die *älteste* verfügbare (sinngemäß `profileSettings[0]`) Profil-Konfiguration angenommen.

=== Generierung
Grundsätzlich wird keine explizite Konfiguration für die Profile benötigt. Als Voreinstellung werden die Profilversionen automatisch aus der Systemzeit und der link:https://github.com/gematik/api-erp/blob/master/docs/erp_fhirversion.adoc[Versionierung der FHIR Profile] abgeleitet.
Diese Voreinstellung lässt sich darüber hinaus auf mehreren Wegen umkonfigurieren:

- hartkodiert beim Aufruf der FHIR Ressourcen Builder (optional)
- Definition einer bestimmten Profilversion über die *System Properties* beim Aufruf z.B. `-kbv.ita.erp=1.0.2`
- Definition einer bestimmten Profilkonfiguration über die *System Properties* beim Aufruf z.B. `-Derp.fhir.profile=1.1.1`
- Definition einer bestimmten Profilkonfiguration über die *Environment Variablen* vor dem Aufruf z.B. `export ERP_FHIR_PROFILE=1.2.0`
- Voreinstellung gemäß der Systemzeit

Die Priorität der Konfigurationen nimmt dabei von oben nach unten ab. Das heißt eine hartkodierte Version, sofern angegeben, wird alle anderen Konfigurationen immer überschreiben. Wohingegen die Konfiguration über eine Umgebungsvariable über die System Properties weiter überschrieben werden kann.