
== Anwendungsfälle
Nachfolgend werden die gängigsten Anwendungsfälle beschrieben, die mit {APP} umgesetzt werden können.

=== FHIR Ressourcen generieren
Das {APP} ist in der Lage viele der im E-Rezept verwendeten FHIR Ressourcen über das CLI zu generieren. Nachfolgend werden exemplarisch die gebräuchlichsten Ressourcen generiert. Die Anzahl der Optionen und Parameter ist sehr vielfältig und kann daher nicht komplett demonstriert werden.

[NOTE]
Die meisten Optionen sind optional und werden, wenn sie fehlen, mit validen Default- bzw. Zufalls-Werten belegt.
Die jeweiligen Optionen können der Hilfe (`erpf generate <CMD> --help`) bzw. der Manpages (`man erpf generate <CMD>`) entnommen werden. Hier werden in der Regel auch die Default-Werte aufgeführt. Führt eine optionale Option in der Hilfe keinen Defautl-Wert auf, so wird in den meisten Fällen hier ein valider Zufalls-Wert benutzt.

==== KBV-Practitioner generieren
Um einen link:https://simplifier.net/packages/kbv.ita.for/1.1.0/files/720095[KBV_PR_FOR_Practitioner] zu generieren, kann das Sub-Kommando `generate kbvpractitioner` verwendet werden. Im nachfolgendem Beispiel wird ein *Zahnarzt* mit dem Namen *Adelheid Ulmenwald* und einer zufälligen ZANR generiert.

[source,shell]
----
erpf generate kbvpractitioner --doc="Adelheid Ulmenwald" --qualification=DENTIST
----

==== KBV-Organization generieren
Um eine link:https://simplifier.net/packages/kbv.ita.for/1.1.0/files/720093[KBV_PF_FOR_Organization] zu generieren, kann das Sub-Kommando `generate kbvorganization` verwendet werden. Im nachfolgenden Beispiel wird eine *Arztpraxis Bernd Claudius* mit der BSNR *123456789* mit einer zufälligen Adresse generiert.

[source,shell]
----
erpf generate kbvorganization --organization="Arztpraxis Bernd Claudius" --bsnr=123456789
----

==== KBV-Patient generieren
Um eine link:https://simplifier.net/packages/kbv.ita.for/1.1.0/files/720094[KBV_PF_FOR_Patient] zu generieren, kann das Sub-Kommando `generate kbvpatient` verwendet werden. Im nachfolgenden Beispiel wird eine *PKV*-Versicherte mit dem Namen *Leonie Hütter* und der KVNR *X123456789* generiert.

[source,shell]
----
erpf generate kbvpatient --patient="Leonie Hütter" --kvnr=X123456789 --insurance-type=PKV
----

==== KBV-Coverage generieren
Um eine link:https://simplifier.net/packages/kbv.ita.for/1.1.0/files/720092[KBV_PF_FOR_Coverage] zu generieren, kann das Sub-Kommando `generate kbvcoverage` verwendet werden. Im nachfolgenden Beispiel wird eine Krankenkasse mit dem Namen *ABC Nord* mit der IKNR *123456789* und WOP in *Berlin* generiert.

[source,shell]
----
erpf generate kbvcoverage --insurance-name="ABC Nord" --iknr=123456789 --wop=BERLIN
----

Hat man die IKNR einer bestimmten Krankenkasse direkt vorliegen, dann kann man sich den Parameter `--insurance-name` im Grunde auch sparen. Die {APP} ist durchaus in der Lage die gängigsten Krankenkassen anhand der IKNR direkt zu mappen. Mit dem folgenden Aufruf kann z.B. eine Coverage-Ressource für die Berufsgenossenschaft **GUVV Hannover** generiert werden:

[source,shell]
----
erpf generate kbvcoverage --iknr=120391764 --wop=NIEDERSACHSEN
----

Wenn die IKNR {APP} bekannt ist (wie in diesem Fall die GUVV Hannover), dann wird der Name und die Versicherungsart automatisch gesetzt.

[CAUTION]
Dieser Mechanismus kann über `--insurance-name` und `--coverage-type` überschrieben werden. Wird allerdings `--coverage-type` abweichend vom bekannten Typ gesetzt, dann kann der richtige Name der Versicherung unter Umständen nicht mehr korrekt aufgelöst werden. Als Fallback-Variante wird immer ein zufälliger Name generiert.

[TIP]
Die bekannten Krankenkassen können über das Kommando `erpf lscov` aufgelistet werden (siehe <<list_insurances_cmd>>)

==== KBV-Medication generieren
Um eine link:https://simplifier.net/packages/kbv.ita.erp/1.1.0/files/720161[KBV_PR_ERP_Medication_PZN] zu generieren, kann das Sub-Kommando `generate kbvmedication` verwendet werden. Im nachfolgenden Beispiel wird eine Medikation für *Vitamin D3 Hevert 4.000 I.E. Tabletten - 90 St.* mit der PZN *11295470* und der Normgröße *N3* mit *90 Stk.* Inhalt generiert.

[source,shell]
----
erpf generate kbvmedication --drugname="Vitamin D3 Hevert 4.000 I.E. Tabletten - 90 St." --pzn=11295470 --amount=90 --size=N3
----

==== KBV-Medication-Request generieren
Um eine link:https://simplifier.net/packages/kbv.ita.erp/1.1.0/files/720163[KBV_PR_ERP_Prescription] zu generieren, kann das Sub-Kommando `generate kbvmedicationrequest` verwendet werden. Im nachfolgenden Beispiel wird eine *Verordnung* für *2* Packungen mit der Dosieranweisung *0-0-1-0* und der Möglichkeit für ein *Ersatzpräparat* (*Aut-idem*) generiert.

[source,shell]
----
erpf generate kbvmedicationrequest --packages=2 --dosage=0-0-1-0 --aut-idem
----

==== KBV-Bundles generieren
Um FHIR-Ressourcen zu generieren, wird das Sub-Kommando `generate kbvbundle` verwendet. Der nachfolgende Aufruf generiert 10 link:https://simplifier.net/packages/kbv.ita.erp/1.0.2[KBV_PR_ERP_Bundle] und legt diese im Pfad `./kbv_bundles` ab.

[source,shell]
----
erpf generate kbvbundle -n10 ./kbv_bundles
----

[NOTE]
Das KBV-Bundle setzt sich aus den vorherigen Ressourcen wie z.B. Patient und Practitioner zusammen. Hier können deshalb auch sämtliche Optionen aus den jeweiligen einzelnen Ressourcen wie z.B. `--doc` und `--kvnr` verwendet werden.

=== FHIR-Ressourcen transkodieren
FHIR-Ressourcen können zwischen den Kodierungtypen `JSON` und `XML` _transkodiert_ werden. D.h. habe ich z.B. KBV-Bundles in `XML` vorliegen, benötige diese allerdings in `JSON`, dann kann ich diese über das Sub-Kommando `transcode` umwandeln lassen.

[source,shell]
----
erpf transcode -r ./kbv_bundles ./kbv_bundles_json
----

=== FHIR-Ressourcen validieren
FHIR-Ressourcen können gegen die FHIR-Profile mit dem Sub-Kommando `validate` validiert werden. Für die Validierung kommt link:https://hapifhir.io/[HAPI FHIR] zusammen mit der link:#list_profiles_cmd[Profilierung] für das E-Rezept zum Einsatz.

[source,shell]
----
erpf validate -r ./kbv_bundles
----

=== FHIR-Ressourcen ersetzen
Es kommt vor, dass man bestimmte Werte in bestehenden FHIR-Ressourcen ersetzen möchte. Hierzu gibt es das Sub-Kommando `replace`

==== KVNR ersetzen
Um in bestehenden FHIR-Ressourcen die KVNR des Versicherten zu ersetzen, kann das folgende Kommando genutzt werden:

[source,shell]
----
erpf replace kvnr --to X123123123,Z000111222 ./kbv_bundles ./kbv_bundles_replaced
----

Damit werden sämtliche KbvBundles innerhalb von `./kbv_bundles` eingelesen und die KVNR des Versicherten durch KVNR(s) aus dem Parameter `--to` ersetzt.
Der Parameter `--to` akzeptiert sowohl eine komma-separierte Liste an KVNRs als auch eine einzelne KVNR. Im Fall einer komma-separierten Liste an KVNRs werden pro KVNR eine neue Kopie des ursprünglichen KbvBundles angelegt. Konkret heißt das: wenn sich im Input-Verzeichnis `./kbv_bundles` z.B. 5 KbvBundles befinden und über den Parameter `--to` werden 2 KVNRs übergeben, dann werden im Ziel-Verzeichnis `./kbv_bundles_replaced` insgesamt 10 KbvBundles generiert.

=== KBV-Bundles anonymisieren
Vorhandene KBV-Bundles können persönliche Daten über Patient oder verordnende Ärzte enthalten. Bei der Fehler-Analyse (insbesondere bei PU-Rezepten) und Weitergabe von KBV-Bundles mit persönlichen Daten müssen diese zunächst _anonymisiert_ werden. Über das Kommando `anonymize` können die persönlichen Daten automatisiert anonymisiert werden:

[source,shell]
----
erpf anonymize ./kbv_bundles ./kbv_bundles_anonymized
----

In der Standardkonfiguration werden die Identifikatoren (z.B. KVNR und LANR) durch valide Zufallswerte ersetzt und sonstige persönliche Daten nach einer `CharacterReplacementStrategy` ersetzt. Alternativ kann man mit der folgenden Konfiguration eine vollständige "Schwärzung" der persönlichen Daten erzwingen:

[source,shell]
----
erpf anonymize --blacking --id-anonymization=BLACKING ./kbv_bundles ./kbv_bundles_anonymized
----

Mittels `--blacking` wird konfiguriert, dass persönliche Daten wie z.B. Namen und Adressen mit `*` "geschwärzt" werden. Separat dazu wird über `--id-anonymization=BLACKING` konfiguriert, dass auch die Identifikatoren (z.B. KVNR und LANR) komplett "geschwärzt" werden.

=== Krankenkasse auflisten [[list_insurances_cmd]]
Mit dem nachfolgenden Kommando können die Krankenkassen die {APP} bekannt sind aufgelistet werden:

[source,shell]
----
erpf lscov --insurance-type PKV
----