/*
 * Copyright 2025 gematik GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * *******
 *
 * For additional notes and disclaimer from gematik and in case of changes by gematik find details in the "Readme" file.
 */

package de.gematik.test.erezept.fhir.r4.erp.tprescription;

import static de.gematik.test.erezept.fhir.valuesets.eu.EuPartNaming.*;

import ca.uhn.fhir.model.api.annotation.ResourceDef;
import de.gematik.bbriccs.fhir.coding.exceptions.MissingFieldException;
import de.gematik.test.erezept.fhir.r4.ErpFhirResource;
import de.gematik.test.erezept.fhir.values.PrescriptionId;
import org.hl7.fhir.r4.model.Parameters;

@ResourceDef(name = "Parameters")
public class ErpTPrescriptionCarbonCopy extends Parameters implements ErpFhirResource {

  @Override
  public String getDescription() {
    return "This 'CarbonCopy is the Printout generated by ErpFD and sent to BFarm Backend to"
        + " persist";
  }

  public ErpTPrescriptionMedication getMedicationFromPrescription() {
    return this.getRxPrescriptionParameter().getPart().stream()
        .filter(p -> p.getName().equals(MEDICATION.getCode()))
        .map(p -> ErpTPrescriptionMedication.fromMedication(p.getResource()))
        .findFirst()
        .orElseThrow(() -> new MissingFieldException(this.getClass(), MEDICATION.getCode()));
  }

  public ErpTPrescriptionMedication getMedicationFromDispensation() {
    return this.getRxDispensationParameter().getPart().stream()
        .filter(p -> p.getName().equals(DISPENSEINFORMATION.getCode()))
        .flatMap(
            part -> part.getPart().stream().filter(pP -> pP.getName().equals(MEDICATION.getCode())))
        .map(p -> ErpTPrescriptionMedication.fromMedication(p.getResource()))
        .findFirst()
        .orElseThrow(() -> new MissingFieldException(this.getClass(), MEDICATION.getCode()));
  }

  public PrescriptionId getPrescriptionId() {
    return PrescriptionId.from(
        this.getRxPrescriptionParameter().getPart().stream()
            .filter(p -> p.getName().equals(PRESCRIPTION_ID_CAMELCASE.getCode()))
            .map(p -> p.getValue().castToIdentifier(p.getValue()).getValue())
            .findFirst()
            .orElseThrow(
                () ->
                    new MissingFieldException(
                        this.getClass(), PRESCRIPTION_ID_CAMELCASE.getCode())));
  }

  private ParametersParameterComponent getRxDispensationParameter() {
    return this.getParameter().stream()
        .filter(p -> p.getName().equals(RX_DISPENSATION.getCode()))
        .findFirst()
        .orElseThrow(() -> new MissingFieldException(this.getClass(), RX_DISPENSATION.getCode()));
  }

  private ParametersParameterComponent getRxPrescriptionParameter() {
    return this.getParameter().stream()
        .filter(p -> p.getName().equals(RX_PRESCRIPTION.getCode()))
        .findFirst()
        .orElseThrow(() -> new MissingFieldException(this.getClass(), RX_PRESCRIPTION.getCode()));
  }
}
