import http-client.env.json

@doctor = 6a7f66bc2bb0f4cd76deaa260abbb484
#@doctor = 5dd78b5f4376fa876b512452b19380a9


### prescribe pharmaceutical with FHIR+XML example file
# @id DOC-PRESCRIBE-01
POST {{host}}/doc/{{doctor}}/xml/prescribe
Content-Type: application/xml
apikey: {{apikey}}

< ../../erp-fhir/src/test/resources/fhir/valid/kbv/1.3.1/Beispiel_1_PZN.xml
> {%
    client.assert(response.status == 202, "prescribing with FHIR+XML template must work")
    console.log("Created prescription: " + client.global.get("prescriptionId"))
    client.global.set("prescriptionId", response.body["prescriptionId"])
    client.global.set("accessCode", response.body["accessCode"])
%}

### DOC-PHARMACEUTICAL-PRESCRIBE-02
# prescribe a completly random pharmaceutical prescription
POST {{host}}/doc/{{doctor}}/prescribe
Content-Type: application/json
apikey: {{apikey}}

{
  "patient": {
    "kvnr": "S040464113"
  }
}
> {%
  client.assert(response.status == 202, "prescribing with FHIR+XML template must work")
  console.log("Created prescription: " + client.global.get("prescriptionId"))
  client.global.set("prescriptionId", response.body["prescriptionId"])
  client.global.set("accessCode", response.body["accessCode"])
%}

### DOC-PHARMACEUTICAL-PRESCRIBE-03
# prescribe a completly random T-E-Rezept prescription
POST {{host}}/doc/{{doctor}}/prescribe
Content-Type: application/json
apikey: {{apikey}}

{
  "patient": {
    "kvnr": "S040464113"
  },
  "medication": {
    "category": "02"
  }
}

### DOC-PHARMACEUTICAL-DELETE-01
# prescribe a completly random pharmaceutical prescription
DELETE {{host}}/doc/{{doctor}}/abort?taskId=160.000.007.417.811.73&ac=3b128e9730fb02631187ff08dbb320a1956e4458e67e26f7e2a1f74c8c81b138
Content-Type: application/json
apikey: {{apikey}}

