
@actor = 886c6eda7dd5a1c6b1d112907f544d3
@taskId = 160.000.117.436.367.97
@accessCode = a3400dfbf5adf7eb57899f86c28fa2ca95417afd9ed00b43e74622a457b47de5
@secret = 7333f57e07b646c40a5131c8c53c1df7527068bdc8e8c44307ad9a3ce474ab50

### PHARM-ACCEPT-PHARMACEUTICAL-01
POST {{host}}/pharm/{{actor}}/accept?taskId={{taskId}}&ac={{accessCode}}
apikey: {{apikey}}

### PHARM-REJECT-PHARMACEUTICAL-01
POST {{host}}/pharm/{{actor}}/reject?taskId={{taskId}}&secret={{secret}}
apikey: {{apikey}}

### PHARM-ABORT-PHARMACEUTICAL-01
DELETE {{host}}/pharm/{{actor}}/abort?taskId={{taskId}}&secret={{secret}}
apikey: {{apikey}}

### PHARM-CLOSE-PHARMACEUTICAL-01
POST {{host}}/pharm/{{actor}}/close?taskId={{taskId}}&secret={{secret}}
Content-Type: application/json
apikey: {{apikey}}

### PHARM-CLOSE-PHARMACEUTICAL-02
# close a prescription by providing a GEM_ERP_PR_PAR_CloseOperation_Input FHIR+XML template
POST {{host}}/pharm/{{actor}}/xml/close?taskId={{taskId}}&secret={{secret}}
Content-Type: application/fhir+xml
apikey: {{apikey}}

< ../../../../../erp-fhir/src/test/resources/fhir/valid/erp/1.5.0/close/PZN_Nr33_MedicationDispense.xml

### PHARM-RECEIPT-REFETCH-01
GET {{host}}/pharm/{{actor}}/receipt?taskId={{taskId}}&secret={{secret}}
Accept: application/fhir+xml
apikey: {{apikey}}

### DMC-RENDER-PRESCRIPTION-01
GET {{host}}/prescription/dmc/render?taskId={{taskId}}&ac={{accessCode}}
Accept: image/png
apikey: {{apikey}}