activeEnvironment: TU

pspClientConfig:

actors:
  doctors:
    - name: Bernd Claudius
      smcbIccsn: 80276001011699910102 #Praxis Damian Claudius
      hbaIccsn: 80276001011699910100  #Arzt Bernd Claudius
      qualificationType: Arzt
      konnektor: Soft-Konn
      validateResponse: false

    - name: Dr. Schraßer
      smcbIccsn: 80276883110000117369 #Praxis Bloch-Bauer
      hbaIccsn: 80276883110000095767 #Arzt Sam Schraßer
      qualificationType: Arzt
      konnektor: Soft-Konn
      validateResponse: false

    - name: Gündüla Gunther
      smcbIccsn: 80276001011699910102 #Praxis Damian Claudius
      hbaIccsn: 80276001081699900578 #Arzt Gunther
      qualificationType: Zahnarzt
      konnektor: Soft-Konn
      validateResponse: false

  pharmacies:
    - name: Am Flughafen
      smcbIccsn: 80276883110000116873
      konnektor: Soft-Konn
      validateResponse: false


    - name: Stadtapotheke
      smcbIccsn: 80276883110000116872
      konnektor: Soft-Konn
      validateResponse: false

    - name: Am Waldesrand
      smcbIccsn: 80276001011699900861
      konnektor: Soft-Konn
      validateResponse: false

    - name: Adelheid Ulmendorfer
      smcbIccsn: 80276001011699902301
      konnektor: Soft-Konn
      validateResponse: false

    - name: Bernd Ulmendorfer
      smcbIccsn: 80276001011699902302
      konnektor: Soft-Konn
      validateResponse: false

    - name: Christine Ulmendorfer
      smcbIccsn: 80276001011699902303
      konnektor: Soft-Konn
      validateResponse: false

  apothecaries:
    - name: Amanda Albrecht
      hbaIccsn: 80276001081699900579
      konnektor: Soft-Konn

    - name: Finn-Louis Nullmayr
      hbaIccsn: 80276883110000121166
      algorithm: E256
      konnektor: Soft-Konn

  patients:
    - name: Fridolin Straßer
      egkIccsn: 80276883110000113311

    - name: Hanna Bäcker
      egkIccsn: 80276883110000108142

    - name: Sina Hüllmann
      egkIccsn: 80276883110000113298

    - name: Leonie Hütter
      egkIccsn: 80276883110000113312

    - name: Günther Angermänn
      egkIccsn: 80276883110000113323


    - name: Aenna Gondern
      egkIccsn: 80276881025548431301

environments:
  - name: TU
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    ti:
      discoveryDocumentUrl: https://idp-test.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-test.zentral.erp.splitdns.ti-dienste.de
      subscriptionServiceUrl: wss://subscription-test.zentral.erp.splitdns.ti-dienste.de/subscription
    internet:
      discoveryDocumentUrl: https://idp-test.app.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-test.app.ti-dienste.de

  - name: RU
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    ti:
      discoveryDocumentUrl: https://idp-ref.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-ref.zentral.erp.splitdns.ti-dienste.de
      subscriptionServiceUrl: wss://subscription-ref.zentral.erp.splitdns.ti-dienste.de/subscription
    internet:
      discoveryDocumentUrl: https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-ref.app.ti-dienste.de

  - name: RU-DEV
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    ti:
      discoveryDocumentUrl: https://idp-ref.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-dev.zentral.erp.splitdns.ti-dienste.de
      subscriptionServiceUrl: wss://subscription-ref.zentral.erp.splitdns.ti-dienste.de/subscription
    internet:
      discoveryDocumentUrl: https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-dev.app.ti-dienste.de


  - name: LOCAL
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    ti:
      discoveryDocumentUrl: http://127.0.0.1:8590/auth/realms/idp/.well-known/openid-configuration
      fdBaseUrl: http://127.0.0.1:3000
      subscriptionServiceUrl: wss://127.0.0.1:3000/subscription
      userAgent: eRp-Testsuite
    internet:
      discoveryDocumentUrl: http://127.0.0.1:8590/auth/realms/idp/.well-known/openid-configuration
      fdBaseUrl: http://127.0.0.1:3000
      xapiKey: refimpldoesnotcheckanyways==
      userAgent: eRp-Testsuite

konnektors:
  - name: KonSim@localhost
    type: remote
    profile: KONSIM
    address: 127.0.0.1:9106
    protocol: http
    context:
      mandantId: Mandant1
      clientSystemId: CS1
      workplaceId: WP1
      userId: user1
    tls:
      keyStore: konsim_mandant1_keystore.p12
      keyStorePassword: "00"
      trustStore: konsim_truststore.jks
      trustStorePassword: "gematik"

  - name: Soft-Konn
    type: local

