

doctorClients:
  - name: Bernd Claudius
    smcbIccsn: 80276001011699910102
    hbaIccsn: 80276001081699900578
    algorithm: R2048
    qualificationType: Arzt
    konnektor: Soft-Konn
    clientId: gematikTestPs
    clientType: Primärsystem
    redirectUrl: http://test-ps.gematik.de/erezept
    discoveryDocumentUrl: https://idp-ref.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
    fdBaseUrl: https://erp-ref.zentral.erp.splitdns.ti-dienste.de
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    acceptMime: application/fhir+xml
    sendMime: application/fhir+xml

  - name: Gündüla Gunther
    smcbIccsn: 8027600101169991010
    hbaIccsn: 80276001081699900578
    algorithm: R2048
    qualificationType: Zahnarzt
    konnektor: Soft-Konn
    clientId: gematikTestPs
    clientType: Primärsystem
    redirectUrl: http://test-ps.gematik.de/erezept
    discoveryDocumentUrl: https://idp-ref.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
    fdBaseUrl: https://erp-ref.zentral.erp.splitdns.ti-dienste.de
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    acceptMime: application/fhir+xml
    sendMime: application/fhir+xml

pharmacyClients:
  - name: Am Flughafen
    smcbIccsn: 80276883110000116873
    algorithm: R2048
    konnektor: Soft-Konn
    clientId: gematikTestPs
    clientType: Primärsystem
    redirectUrl: http://test-ps.gematik.de/erezept
    discoveryDocumentUrl: https://idp-ref.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
    fdBaseUrl: https://erp-ref.zentral.erp.splitdns.ti-dienste.de
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    acceptMime: application/fhir+xml
    sendMime: application/fhir+xml

  - name: NordApotheke
    smcbIccsn: 80276883110000092475
    algorithm: R2048
    konnektor: Soft-Konn
    clientId: gematikTestPs
    clientType: Primärsystem
    redirectUrl: http://test-ps.gematik.de/erezept
    discoveryDocumentUrl: https://idp-ref.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
    fdBaseUrl: https://erp-ref.zentral.erp.splitdns.ti-dienste.de
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    acceptMime: application/fhir+xml
    sendMime: application/fhir+xml

pharmacists:
  - name: Amanda Albrecht
    hbaIccsn: 80276001081699900579
    algorithm: R2048
    konnektor: Soft-Konn

patientClients:
  - name: Fridolin Straßer
    egkIccsn: 80276883110000113311
    algorithm: R2048
    clientId: gematikTestPs   # what is a valid clientId for FdV?
    clientType: App
    redirectUrl: http://test-ps.gematik.de/erezept
    discoveryDocumentUrl: https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration
    fdBaseUrl: https://erp-ref.app.erp.ti-dienste.de
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    acceptMime: application/fhir+json
    sendMime: application/fhir+json

  - name: Hanna Bäcker
    egkIccsn: 80276883110000108142
    algorithm: R2048
    clientId: gematikTestPs   # what is a valid clientId for FdV?
    clientType: App
    redirectUrl: http://test-ps.gematik.de/erezept
    discoveryDocumentUrl: https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration
    fdBaseUrl: https://erp-ref.app.erp.ti-dienste.de
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    acceptMime: application/fhir+json
    sendMime: application/fhir+json