== cURLs
Mit diesen cURL aufrufen kann der gesamte Workflow für ein E-Rezept durchlaufen werden. Diese Beispiele dienen lediglich zu Dokumentationszwecken.

[IMPORTANT]
In sämtlichen nachfolgenden cURL-Aufrufen wird ein Header für den API-Key benötigt. Um die Aufrufe möglichst kurzzuhalten, empfiehlt es sich, den API-Key als Umgebungsvariable unter `$ERPIONE_API_KEY` abzulegen. Diese Umgebungsvariable wird dann auch so direkt von der {name-erpione} nachgenutzt.

=== Akteure abrufen
In den meisten der nachfolgenden Aufrufe, wird stets ein bestimmter Akteur benötigt, der die Operationen ausführen soll. Jeder Akteur hat eine eigene ID, über die er adressiert werden kann. Um die IDs der Akteure auszulesen, bietet {name-primsys} den Endpunkt `/actors` an:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" https://erpps-test.dev.gematik.solutions/actors | jq
----

=== E-Rezept ausstellen
Um ein E-Rezept mit einem bestimmten Arzt auszustellen, bietet {name-primsys} den Endpunkt `/prescribe` an. Dieser Endpunkt erwartet im Request-Body ein JSON-Objekt, woraus der Verordnungsdatensatz dann erstellt wird.

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" https://erpps-test.dev.gematik.solutions/doc/6a7f66bc2bb0f4cd76deaa260abbb484/prescribe -d '{"patient": {"kvnr": "K220635158"}, "medication": {"pzn": "00571748"}}' | jq
----

Alternativ bietet {name-primsys} auch einen XML-Endpunkt `/xml/prescribe` an, der ein KBV-Bundle (als XML) entgegennehmen kann. Dieses KBV-Bundle wird dann nahezu unverändert, signiert und am Fachdienst ausgestellt.

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/xml" https://erpps-test.dev.gematik.solutions/doc/6a7f66bc2bb0f4cd76deaa260abbb484/xml/prescribe -d "@/home/user/kbv_bundle.xml" | jq
----

[NOTE]
Der Content-Type-Header ist hier wichtig und muss zwingend zu `application/xml` anstatt `applicathon/json` wie in den meisten anderen Endpunkten abgeändert werden.

=== E-Rezept akzeptieren
Um ein E-Rezept als Apotheke zu akzeptieren, bietet {name-primsys} den Endpunkt `/accept` an.

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" -X POST https://erpps-test.dev.gematik.solutions/pharm/84b5f179e0451d03ea8c8948f52687b8/accept?taskId=<TASK-ID>&ac=<ACCESS-CODE> | jq
----

=== Akzeptiertes E-Rezept zurückgeben
Um ein bereits akzeptiertes E-Rezept als Apotheke wieder zurückzugeben, bietet {name-primsys} den Endpunkt `/reject`

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" -X POST https://erpps-test.dev.gematik.solutions/pharm/84b5f179e0451d03ea8c8948f52687b8/reject?taskId=<TASK-ID>&ac=<ACCESS-CODE>&secret=<SECRET> | jq
----

=== Akzeptiertes E-Rezept dispensieren
Um ein bereits akzeptiertes E-Rezept als Apotheke zu dispensieren, bietet {name-primsys} den Endpunkt `/close` an. Dieser Endpunkt nimmt *optional* einen Body entgegen.

Wird *kein* Body mitgegeben, dann wird das ursprünglich verschriebene Medikament dispensiert:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" -X POST https://erpps-test.dev.gematik.solutions/pharm/84b5f179e0451d03ea8c8948f52687b8/close?taskId=<TASK-ID>&ac=<ACCESS-CODE>&secret=<SECRET> | jq
----

Wird *ein* Body mitgegeben, dann wird ein alternatives Medikament (oder auch mehrere) dispensiert:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" -X POST https://erpps-test.dev.gematik.solutions/pharm/84b5f179e0451d03ea8c8948f52687b8/close?taskId=<TASK-ID>&ac=<ACCESS-CODE>&secret=<SECRET> -d '[{"pzn": "17260627", "batch": {"lotNumber": 123123 }}]' | jq
----

[IMPORTANT]
Der JSON-Body ist eine Liste von Medikamenten die dispensiert werden sollen. Hier muss also genau darauf geachtet werden, dass der Body innerhalb von `[]` steht, auch wenn nur ein Medikament dispensiert wird.

=== Communications abrufen
Um als Apotheke Nachrichten abzurufen, bietet {name-primsys} den Endpunkt `/communications` an.
Im einfachsten Fall können für eine bestimmte Apotheke die *neuesten* (maximal 50) Nachrichten über den folgenden Aufruf abgerufen werden:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" -X GET https://erpps-test.dev.gematik.solutions/pharm/84b5f179e0451d03ea8c8948f52687b8/communications | jq
----

Möchte man stattdessen die *ältesten* Nachrichten abrufen, dann kann der Query-Parameter `sort` verwendet werden:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" -X GET https://erpps-test.dev.gematik.solutions/pharm/84b5f179e0451d03ea8c8948f52687b8/communications?sort=lifo | jq
----

[NOTE]
====
- Der Wert des Query-Parameters `sort` ist *case-insensitive*, d.h. sowohl "lifo", "Lifo" als auch "LIFO" sind valide Werte.

- Neben "LIFO" können synonym auch "ASCENDING" und "OLDEST" verwendet werden

- Die Sortierung nach dem FIFO-Prinzip ist der Default. Das heißt, wird *kein* `sort` Parameter oder ein invalider Wert angegeben, werden die neuesten Communications abgerufen.
====

Mittels der Query-Parameter `receiver` und `sender` können Communications für bestimmte Empfänger oder Sender gefiltert werden.

Um z.B. Nachrichten abzurufen, die ein Versicherter mit der KVNR `X110407071` an die jeweilige Apotheke (mit der PrimSys-ID `84b5f179e0451d03ea8c8948f52687b8`) gesendet hat, kann mittels folgendem cURL erreicht werden:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" -X GET https://erpps-test.dev.gematik.solutions/pharm/84b5f179e0451d03ea8c8948f52687b8/communications?sender=X110407071 | jq
----

Auf der anderen Seite können mittels `receiver=X110407071` Nachrichten abgerufen werden, welche die jeweilige Apotheke an den Versicherten gesendet hat:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" -X GET https://erpps-test.dev.gematik.solutions/pharm/84b5f179e0451d03ea8c8948f52687b8/communications?receiver=X110407071 | jq
----

[IMPORTANT]
====
Die Angabe der Query-Parameter `receiver` impliziert, dass damit nur `REPLY`-Nachrichten gefunden werden können.
Auf der anderen Seite impliziert der Query-Parameter `sender`, dass damit nur `INFO_REQ`- und `DISP_REQ`-Nachrichten gefunden werden können.

Um einen vollständigen Nachrichten-Verlauf zwischen der Apotheke und nur einem bestimmten Versicherten abzurufen, bedarf es daher mindestens von zwei Requests.

Sowohl PrimSys als auch der Fachdienst erlauben es sowohl `receiver` als auch `sender` zusammen anzugeben.
In diesem Fall MUSS dann aber immer einer der beiden Parameter die Telematik-ID der jeweiligen Apotheke enthalten, da sonst die Suchanfrage zu einem leeren Ergebnis führt.
====

=== Lokalen Rezept-Speicher abrufen
Mit {name-primsys} können auch alle E-Rezepte abgerufen werden, die dem Service bekannt sind.

Um *offene* E-Rezepte abzurufen, die über {name-primsys} erstellt wurden:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" https://erpps-test.dev.gematik.solutions/prescription/prescribed | jq
----

Um *akzeptierte* E-Rezepte abzurufen, die über {name-primsys} akzeptiert wurden:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" https://erpps-test.dev.gematik.solutions/prescription/accepted | jq
----

Um *dispensierte* E-Rezepte abzurufen, die über {name-primsys} dispensiert wurden:

[source,shell]
----
curl -H "apikey: $ERPIONE_API_KEY" -H "Content-Type: application/json" https://erpps-test.dev.gematik.solutions/prescription/dispensed | jq
----