<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>erezept-testsuite</artifactId>
        <groupId>de.gematik.test.erezept</groupId>
        <version>1.7.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <name>ERP Cucumber-Steps Commons</name>
    <description>Common Cucumber steps and utilities for ERP tests</description>

    <artifactId>erp-bdd-common</artifactId>

    <dependencies>
        <dependency>
            <groupId>de.gematik.test.erezept</groupId>
            <artifactId>erp-config-data</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.test.erezept</groupId>
            <artifactId>erp-fhir</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.test.erezept</groupId>
            <artifactId>erp-fhir</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.gematik.test.erezept</groupId>
            <artifactId>smartcard</artifactId>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.xml.bind</groupId>
                    <artifactId>jaxb-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay</artifactId>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-ensure</artifactId>
        </dependency>
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <!-- required by the Doctor to generate DMC for "low-detail" Prescription -->
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.zxing</groupId>
            <artifactId>javase</artifactId>
        </dependency>
        <!-- new dependencies-->
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>crypto-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>konnektor-ws-api-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>konnektor-client-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>softkon-service-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>remotekon-service-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>cats-client-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>resource-loader-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>vsdm-check-digit-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.test.erezept</groupId>
            <artifactId>erp-client</artifactId>
        </dependency>
    </dependencies>
    <!-- new plugin maven-jar-plugin because we want to use questions (in test) from erp-bdd-comon in erp-client-fdv-steps-->
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
