<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.gematik.test.erezept</groupId>
        <artifactId>erezept-testsuite</artifactId>
        <version>1.7.1</version>
    </parent>

    <artifactId>erp-config</artifactId>
    <name>E-Rezept TestSuite Configurations</name>
    <description>E-Rezept TestSuite Configurations parent</description>
    <packaging>pom</packaging>

    <modules>
        <module>erp-config-data</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>de.gematik.bbriccs</groupId>
                <artifactId>feature-toggle-brick</artifactId>
                <version>${version.bricks}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>tools.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
    </dependencies>
</project>
