:imagesdir: ./images
:caution-caption: Achtung
:important-caption: Wichtig
:note-caption: Hinweis
:tip-caption: Tip
:warning-caption: Warnung
:toc: macro
:toclevels: 3
:toc-title: Inhaltsverzeichnis
:hide-uri-scheme:


= Testsuite Konfiguration

== Basiskonfiguration

Jede Software benötigt in einem gewissen Maße eine Konfiguration und das gilt auch für die E-Rezept Testsuite. Die Konfiguration der Testsuite wird ausschließlich im `YAML`-Format definiert.

Die Konfiguration ist in mehrere Abschnitte unterteilt, wobei jeder Abschnitt immer eine bestimmte Teilkomponente der Testsuite konfiguriert.

[source,yaml,linenums]
----
activeEnvironment: TU   # definiert die aktive Testumgebung

actors:                 # definiert die Akteure
  ...

environments:           # definiert die Testumgebungen
  ...

konnektors:             # definiert die Konnektoren
  ...
----

=== Akteure

Die Konfiguration der einzelnen Akteure wird im Abschnitt `actors` definiert. Dieser Abschnitt selbst ist nochmals unterteilt nach den einzelnen Arten der Akteure. Hier wird konkret zwischen Ärzten, Apotheken, Apotheker und Versicherten/Patienten unterschieden.

[source,yaml,linenums]
----
actors:
  doctors:            # definiert die Ärzte
    ...
  pharmacies:         # definiert die Apotheken
    ...
  apothecaries:       # definiert die Apotheker
    ...
  patients:           # definiert die Versicherten/Patieten
    ...
----

Sämtliche Konfigurationen der Akteure sind sogenannte `NamedConfigurations`, d.h diese müssen immer zwingend ein Feld `name` haben über welchen diese in der Testsuite eindeutig referenziert wird.

NOTE: Grundsätzlich sind die meisten konkreten Werte der einzelnen Felder in der Konfiguration Strings bzw. vereinzelt Booleans und werden als solchen auch ausgelesen. Allerdings sind nicht aller String-Felder als Freitexte definierbar. Hinter einigen der Felder sind Enumerationen hinterlegt, die nur eine fest definierte Menge an möglichen Werten entgegennehmen.

Sämtliche Akteure, die aktiv mit dem Fachdienst und IDP kommunizieren teilen sich eine Untermenge an identischen Konfigurationsfeldern:

[cols="3,7,2,1"]
|===
| Feld | Beschreibung | Datentyp | Verpflichtend

| name
| Der Name des Akteurs, über den dieser in der Testsuite referenziert wird
| Freitext
| true

| clientId
| Ist die Client-ID die der Arzt für die Kommunikation mit dem IDP nutzen soll
| Freitext
| false

| redirectUrl
| Ist die URL für den Redirect, den der Arzt für die Kommunikation mit dem IDP nutzen soll
| Freitext
| false

| userAgent
| Ist der User-Agent, den der Arzt für die REST-Kommunikation innerhalb von VAU nutzen soll
| Freitext
| false

| algorithm
| Ist der Crypto-Algorithmus, der für die Smartcards verwendet werden soll. Zur Auswahl stehen hier R2048 und E256 zur Auswahl. Der Default-Wert ist R2048
| Enum
| false

| acceptMime
| Ist der mime-Type der FHIR-Responses die vom Fachdienst akzeptiert/erwartet wird. Für Ärzte und Apotheken ist der Default-Wert `application/fhir+xml`, für Versicherte/Patienten hingegen `application/fhir+json`
| Freitext
| false

| sendMime
| Ist der mime-Type der FHIR-Requests die an den Fachdienst gesendet werden. Für Ärzte und Apotheken ist der Default-Wert `application/fhir+xml`, für Versicherte/Patienten hingegen `application/fhir+json`
| Freitext
| false

| acceptCharset
| Ist das Charset, das vom Client des Arztes erwartet wird. Der Default-Wert ist `utf-8`
| Freitext
| false

| validateRequest
| Gibt an, ob ausgehende FHIR-Requests gegen die Profilierung validiert werden sollen
| Boolean
| false

| validateResponse
| Gibt an, ob eingehende FHIR-Responses gegen die Profilierung validiert werden sollen
| Boolean
| false

|===

In den nachfolgenden Abschnitten werden die spezifischen Felder der jeweiligen Akteure erklärt.

==== Ärzte

Nachfolgend die vollständige Konfiguration für den Arzt `Bernd Claudius`.

[source,yaml,linenums]
----
doctors:
- name: Bernd Claudius
  smcbIccsn: 8027600101169991010
  hbaIccsn: 80276001011699910102
  qualificationType: Arzt
  konnektor: KOCO@kon7
  clientId: gematikClient                           # optional
  redirectUrl: http://test-ps.gematik.de/erezept    # optional
  userAgent: gematik/User/Agent                     # optional
  algorithm: R2048                                  # optional
  acceptMime: application/fhir+xml"                 # optional
  sendMime: application/fhir+xml"                   # optional
  acceptCharset: utf-8                              # optional
  validateRequest: false                            # optional
  validateResponse: false                           # optional

- name: ... # nächster Arzt
----

[cols="3,7,2,1"]
|===
| Feld | Beschreibung | Datentyp | Verpflichtend

| smcbIccsn
| Die ICCSN der SMC-B die von dem Arzt verwendet werden soll
| Freitext
| true

| hbaIccsn
| Die ICCSN des HBA der von dem Arzt verwendet werden soll
| Freitext
| true

| qualificationType
| Die Qualification des Arztes gemäß der link:https://simplifier.net/for/kbvcsforqualificationtype[Profilierung der KBV]. Hier wird der `Display`-Wert aus der Profilierung erwartet
| Enum
| true

| konnektor
| Ist eine Referenz auf den Namen eines konkreten Konnektors aus dem Abschnitt `konnektors`
| Referenz
| true

|===

==== Apotheken

Nachfolgend die vollständige Konfiguration für die Apotheke `Am Flughafe`.

[source,yaml,linenums]
----
pharmacies:
- name: Am Flughafen
  smcbIccsn: 80276883110000116873
  konnektor: Soft-Konn
  clientId: gematikClient                           # optional
  redirectUrl: http://test-ps.gematik.de/erezept    # optional
  userAgent: gematik/User/Agent                     # optional
  algorithm: R2048                                  # optional
  acceptMime: application/fhir+xml"                 # optional
  sendMime: application/fhir+xml"                   # optional
  acceptCharset: utf-8                              # optional
  validateRequest: false                            # optional
  validateResponse: false                           # optional

- name: ... # nächste Apotheke
----

[cols="3,7,2,1"]
|===
| Feld | Beschreibung | Datentyp | Verpflichtend

| smcbIccsn
| Die ICCSN der SMC-B die von der Apotheke verwendet werden soll
| Freitext
| true

| konnektor
| Ist eine Referenz auf den Namen eines konkreten Konnektors aus dem Abschnitt `konnektors`
| Referenz
| true

|===

==== Apotheker

Nachfolgend die vollständige Konfiguration für die Apothekerin `Amanda Albrecht`.

NOTE: Apotheker selbst kommunizieren nie direkt mit dem Fachdienst bzw. dem IDP und haben deshalb keine Konfigurationsfelder für diese Komponenten.

[source,yaml,linenums]
----
apothecaries:
- name: Amanda Albrecht
  hbaIccsn: 80276001081699900579
  konnektor: Soft-Konn
  algorithm: R2048                     # optional

- name: ... # nächste Apotheke
----

[cols="3,7,2,1"]
|===
| Feld | Beschreibung | Datentyp | Verpflichtend

| hbaIccsn
| Die ICCSN des HBA der von dem Apotheker verwendet werden soll
| Freitext
| true

| konnektor
| Ist eine Referenz auf den Namen eines konkreten Konnektors aus dem Abschnitt `konnektors`
| Referenz
| true

|===

==== Versicherte

Nachfolgend die vollständige Konfiguration für den Versicherten `Fridolin Straßer`.

[source,yaml,linenums]
----
patients:
- name: Am Flughafen
  egkIccsn: 80276883110000113311
  clientId: gematikClient                           # optional
  redirectUrl: http://test-ps.gematik.de/erezept    # optional
  userAgent: gematik/User/Agent                     # optional
  algorithm: R2048                                  # optional
  acceptMime: application/fhir+xml"                 # optional
  sendMime: application/fhir+xml"                   # optional
  acceptCharset: utf-8                              # optional
  validateRequest: false                            # optional
  validateResponse: false                           # optional

- name: ... # nächste Apotheke
----

[cols="3,7,2,1"]
|===
| Feld | Beschreibung | Datentyp | Verpflichtend

| egkIccsn
| Die ICCSN der eGK die von dem Versicherten verwendet werden soll
| Freitext
| true

|===

=== Testumgebung

Die Konfiguration der einzelnen Testumgebungen wird im Abschnitt `environments` definiert. Die Testumgebung die verwendet werden soll, wird über die Konfiguration `activateEnvironment` über den Namen einer bestimmten Umgebung gesetzt. Nachfolgend die Konfiguration der `TU` Testumgebung:

[source,yaml,linenums]
----
environments:
  - name: TU
    tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC/
    ti:
      discoveryDocumentUrl: https://idp-test.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-test.zentral.erp.splitdns.ti-dienste.de
      subscriptionServiceUrl: wss://subscription-test.zentral.erp.splitdns.ti-dienste.de/subscription
    internet:
      discoveryDocumentUrl: https://idp-test.app.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-test.app.ti-dienste.de
      xapiKey: 0000000000000000
----

Darüber hinaus bietet jede Umgebung zwei unterschiedliche Routen. Die eine ist öffentlich aus dem Internet (`inernet`) erreichbar und wird ausschließlich von den Versicherten genutzt. Die zweite Route ist nur über die Telematik-Infrastruktur (`ti`) erreichbar und wird von den Primärsystemen verwendet.

[cols="3,7,2,1"]
|===
| Feld | Beschreibung | Datentyp | Verpflichtend

| name
| Der Name der Testumgebung, der über `activeEnvironment` referenziert wird
| Freitext
| true

| tslBaseUrl
| Ist die URL für den TSL-Dienst
| Freitext
| true

| discoveryDocumentUrl
| Ist die URL für das DiscoveryDocument welches für die Kommunikation mit dem IDP benötigt wird
| Freitext
| true

| fdBaseUrl
| Ist die URL des E-Rezept-Fachdienstes
| Freitext
| true

| subscriptionServiceUrl
| Ist die URL für den Subscription-Service des E-Rezept-Fachdienstes. Dieser wird ausschließlich von den Apotheke für die Benachrichtigung über neue Nachrichten verwendet.
| Freitext
| true

| xapiKey
| Ist der X-API-Key den der Versicherte für die Kommunikation mit dem Fachdienst verwenden soll
| Freitext
| true

|===

=== Konnektoren

Die Konfiguration der einzelnen Konnektoren wird im Abschnitt `konnektors` definiert. Der Konnektor der von einm Akteur (Apothek, Apotheker und Arzt) verwendet werden soll, referenzieren die jeweiligen Akteure im Feld `konnektor` über den Namen des jeweiligen Konnektors. Zur Auswahl stehen zwei unterschiedliche Arten von Konnektoren: nämlich ein echter Konnektor (mit SOAP-Kommunikation) und ein __"Soft-Konn"__ der ohne einen echten Konnektor und folglich ohne jegliche SOAP-Kommunikation auskommt. Die Konfigurationen dieser beiden Arten unterscheiden sich. Deshalb werden nachfolgend jeweils ein Konnektor von jeder Art konfiguriert.

[source,yaml,linenums]
----
konnektors:
  - name: KonSim@localhost
    type: remote
    profile: KONSIM
    address: 127.0.0.1:9106
    protocol: http
    context:
      mandantId: Mandant1
      clientSystemId: CS1
      workplaceId: WP1
      userId: user1
    tls:
      keyStore: konsim_mandant1_keystore.p12
      keyStorePassword: "00"
      trustStore: konsim_truststore.jks
      trustStorePassword: "gematik"

  - name: Soft-Konn
    type: local
----

Die nachfolgenden Felder sind für beide Arten von Konnektor identisch.

[cols="3,7,2,1"]
|===
| Feld | Beschreibung | Datentyp | Verpflichtend

| name
| Der Name des Konnektors, über den die Akteure den jeweiligen Konnektor referenzieren
| Freitext
| true

| type
| Ist die Art des Konnektors. Hier gibt es die Unterscheidung zwischen `remote` und `local`
| Enum
| true

|===

Falls ein Konnektor vom Typ `remote` konfiguriert wird, werden zusätzlich die folgenden Felder benötigt:

[cols="3,7,2,1"]
|===
| Feld | Beschreibung | Datentyp | Verpflichtend

| type
| Ist die Art des Konnektors. Hier gibt es die Unterscheidung zwischen `remote` und `local`
| Enum
| true

| profile
| Ist das _"Profil"_ des Konnektors (tatsächlich eigentlich der Hersteller!). Hier stehen die folgenden Werte zur Auswahl: `KONSIM`, `SECUNET`, `RISE` und `CGM`
| Enum
| true

| address
| Ist die Adresse, unter derer der Konnektor erreichbar ist.
| Freitext
| true

| protocol
| Ist das Protokoll, welches für die SOAP-Kommunikation verwendet wird. Hier stehen `http` bzw. `https` zur Auswahl. Wobei die Auswahl `https` zur Folge hat, dass das nachfolgend auch `tls` konfiguriert werden muss.
| Enum
| true

|===

== Individueller Konfigurationsanpassung

Neben der eigentlich Konfiguration der Testsuite existiert zusätzlich die Möglichkeit diese gezielt zu verändern ohne die Basiskonfiguration ändern zu müssen. Dafür unterstützt die Testsuite das __Partial Configuration Substitution__ über zwei Wege.

=== PCS Files

Die `.pcs`-Files sind spezielle Dateien die im Kontext der E-Rezept Testsuite zum Einsatz kommen. Die Struktur dieser Dateien ist an gewöhnliche `.properties`-Files angelehnt, hat allerdings noch einige zusätzliche Eigenschaften.
Diese sollen es dem Benutzer erlauben notwendige Änderungen, die in der Konfiguration auf einem bestimmten Rechner immer vorgenommen werden müssen, in eine separate Datei auszulagern. Damit das `.pcs`-File korrekt eingelesen und ausgewertet werden kann, müssen die folgenden Regeln beachtet werden:

1. Die Datei benötigt zwingend die Dateiendung `.pcs`
2. Die Datei muss im gleichen Pfad mit der `config.yaml` liegen
3. Die Datei muss den `Hostname` des Rechners, auf dem die Testsuite ausgeführt wird im Namen enthalten

TIP: Hierüber lassen sich z.B. sensible Daten wie Passwörter in das `.pcs`-File auslagern und mittels Git von der Versionierung ausschließen.

Wie bereits erwähnt ist die Syntax der `.pcs`-Files an `.properties`-Files angelehnt.
Das nachfolgende Beispiel veranschaulicht die drei wesentlichen Features:

[source,properties]
----
# change the active Environment always to local on my mashine
activeEnvironment = local

# let all doctors and pharmacies use the Soft-Konn
actors.doctors.*.konnektor = Soft-Konn
actors.pharmacies.*.konnektor = Soft-Konn

# except the doctor with Index 0 should use an other Konnektor
actors.doctors.#0.konnektor = KonSim@localhost
----

=== System Properties

Zusätzlich zu den `.pcs`-Files gibt es noch die Möglichkeit die Basiskonfiguration über die System Properties zu verändern. Die Substitution über die System Properties kann mit dem `.pcs`-File kombiniert werden. Dabei wird Konfiguration folgendermaßen eingelesen:

1. Basiskonfiguration aus `config.yaml` einlesen
2. Rechnerspezifische Substitutionen aus `<hostname>.pcs` auf die Basiskonfiguration anwenden
3. Substitutionen aus den System Properties auf die Basiskonfiguration anwenden

Die Syntax der Substitutionen über die System Properties ist nahezu identisch zu der des `.pcs`-Files mit einem kleinen Unterschied: die Properties benötigen den Prefix `erp.config` damit die Testsuite die Properties auch finden kann.

=== Beispielszenario

Schauen wir uns das folgende Szenario an um das Konzept zu verdeutlichen:

[cols="1,10"]
|===

|*Angenommen*
|wir haben die Basiskonfiguration in der `config.yaml` und im gleichen Pfad `myhost.pcs` mit Substitutionen aus dem vorherigen Beispiel

|*Wenn*
|wir die Testsuite mit dem folgenden Kommando auf dem Rechner mit dem Namen `myhost` ausführen:

`user@myhost:~$ java -jar testsuite.jar -Derp.config.activeEnvironment=RU -Derp.config.actors.doctors.#1.konnektor`

|*Dann*
|wird die Testsuite gegen die Testumgebung `RU` ausgeführt

|*Und*
|die konfigurierten Ärzte mit den Indizes `0` und `1` benutzen den Konnektor `KonSim@localhost`

|*Und*
|alle anderen Ärzte und Apotheken benutzen den Konnektor `Soft-Konn`
|===