activeEnvironment: TU

preferManualSteps: false

pspClientConfig:
  url: DUMMY VALUE
  auth: DUMMY VALUE

actors:
  doctors:
    - name: Adelheid Ulmenwald
      smcbIccsn: 80276001011699901102 # Praxis Bernd Rosenstrauch
      hbaIccsn: 80276001011699901501
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Michael Morgenrot
      smcbIccsn: 80276883110000159320 # Reha-Klinik Morgenrot
      hbaIccsn: 80276001011699901501 # HBA von Ulmenwald
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Dr. Schraßer
      smcbIccsn: 80276883110000163972 #Praxis Peer Graf von Müller
      hbaIccsn: 80276883110000170943 # Arzt Max Tangeroal
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Gündüla Gunther
      smcbIccsn: 80276001011699901102 # Praxis Bernd Rosenstrauch
      hbaIccsn: 80276883110000161759
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Michael Meierhofer
      description: "Arzt OHNE Telematik-ID im HBA"
      smcbIccsn: 80276001011699901102 # Praxis Bernd Rosenstrauch
      hbaIccsn: 80276001011699901343
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Norbert Neuland
      description: "Arzt OHNE Telematik-ID im HBA"
      smcbIccsn: 80276001011699901102 # Praxis Bernd Rosenstrauch
      hbaIccsn: 80276001011699901344
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Finn Stauffenberg
      description: "Akteur mit Psychotherapeut-HBA und Psychotherapeutische Praxis SMC-B"
      smcbIccsn: 80276883110000163952 # Psychotherapeutische Praxis Hillbert Freiherr Cördes
      hbaIccsn: 80276883110000163949  # Psychotherapeut Finn Stauffenberg
      algorithm: E256
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Peter Kleinschmidt
      description: "Akteur mit Psychotherapeut-HBA und Psychotherapeutische Praxis SMC-B"
      smcbIccsn: 80276883110000163952 # Psychotherapeutische Praxis Hillbert Freiherr Cördes
      hbaIccsn: 80276883110000163950  # Psychotherapeut Peter Kleinschmidt
      algorithm: E256
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Julian Böcher
      description: "Akteur mit Psychotherapeut-HBA und Psychotherapeutische Praxis SMC-B"
      smcbIccsn: 80276883110000163952 # Psychotherapeutische Praxis Hillbert Freiherr Cördes
      hbaIccsn: 80276883110000163951  # Psychotherapeut Julian Böcher
      algorithm: E256
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Kein Arzt
      description: "Akteur mit Apotheker-HBA und Arztpraxis SMC-B der sich als Arzt ausgibt"
      smcbIccsn: 80276001011699901102 # Praxis Bernd Rosenstrauch
      hbaIccsn: 80276001011699901726
      algorithm: E256
      qualificationType: Arzt
      konnektor: Soft-Konn

    - name: Keine Arztpraxis
      description: "Akteur mit Apotheker-HBA und Apotheken SMC-B der sich als Arzt ausgibt"
      smcbIccsn: 80276883110000163973 # Arminius Apotheke
      hbaIccsn: 80276001011699901726  # Apotheker Nullmayr
      algorithm: E256
      qualificationType: Arzt
      konnektor: Soft-Konn

  pharmacies:
    - name: Am Flughafen
      apoVzdName: Apotheke am FlughafenTEST-ONLY
      smcbIccsn: 80276883110000163973
      konnektor: Soft-Konn

    - name: NordApotheke  # Apotheke mit abgelaufener SMCB
      smcbIccsn: 80276883110000092475
      konnektor: Soft-Konn

    - name: Stadtapotheke
      smcbIccsn: 80276883110000092475
      konnektor: Soft-Konn

    - name: Keine Apotheke
      description: "Apotheke mit der SMC-B einer Arztpraxis"
      smcbIccsn: 80276001011699901102 # Praxis Bernd Rosenstrauch
      konnektor: Soft-Konn

    - name: Am Waldesrand
      smcbIccsn: 80276001011699900861
      konnektor: Soft-Konn

    - name: Adelheid Ulmendorfer
      smcbIccsn: 80276001011699902301
      konnektor: Soft-Konn

    - name: Bernd Ulmendorfer
      smcbIccsn: 80276001011699902302
      konnektor: Soft-Konn

    - name: Christine Ulmendorfer
      smcbIccsn: 80276001011699902303
      konnektor: Soft-Konn

    - name: An der Schule
      smcbIccsn: 80276883110000147759
      konnektor: Soft-Konn


  apothecaries:
    - name: Finn-Louis Nullmayr
      hbaIccsn: 80276001011699901726
      algorithm: E256
      konnektor: Soft-Konn

  patients:
    - name: Fridolin Straßer
      egkIccsn: 80276883110000163961

    - name: Hanna Bäcker
      egkIccsn: 80276883110000163962

    - name: Sina Hüllmann
      egkIccsn: 80276883110000163963

    - name: Leonie Hütter
      egkIccsn: 80276883110000163964

    - name: Günther Angermänn
      egkIccsn: 80276883110000163965

    - name: Aenna Gondern # Kassenidentität ohne validen privaten Schlüssel
      egkIccsn: 80276883110000168560

    - name: Tina Kleinschmidt # Für Egk in der Apotheke / AuditEvents
      egkIccsn: 80276883110000168560

  healthInsurances:
    - name: AOK Bremen
      smcbIccsn: 80276883110000163954
      konnektor: Soft-Konn

  euPharmacies:
    - name: Hannes Vogt
      countryCode: CZ
      smcbIccsn: ncpeh-smb
      pharmacistIdentifier: GLN Person 7601001380592
      organizationIdentifier: GLN 7601001401228

    - name: Martina Gauci
      countryCode: MT
      smcbIccsn: ncpeh-smb
      pharmacistIdentifier: Spiżjar 5351001380592
      organizationIdentifier: 5351001380532

environments:
  - name: TU
    ti:
      tslBaseUrl: http://download-test.tsl.telematik-test/ECC
      discoveryDocumentUrl: https://idp-test.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-test.zentral.erp.splitdns.ti-dienste.de
      subscriptionServiceUrl: wss://subscription-test.zentral.erp.splitdns.ti-dienste.de/subscription
      userAgent: DUMMY VALUE
    internet:
      tslBaseUrl: https://download-test.tsl.ti-dienste.de/ECC
      discoveryDocumentUrl: https://idp-test.app.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-test.app.ti-dienste.de
      xapiKey: DUMMY VALUE
      userAgent: DUMMY VALUE
    epaMockClient:
      epaMockUrl: https://epa-as-mock.test.gematik.solutions:443
      epaMockApiKey: DUMMY VALUE
      logRetrieveInterval: 10000
      maxWait: 360000
    tRegisterMockClient:
      tRegisterMockUrl: https://t-register.test.gematik.solutions

  - name: RU
    ti:
      tslBaseUrl: http://download-ref.tsl.telematik-test/ECC
      discoveryDocumentUrl: https://idp-ref.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-ref.zentral.erp.splitdns.ti-dienste.de
      subscriptionServiceUrl: wss://subscription-ref.zentral.erp.splitdns.ti-dienste.de/subscription
      userAgent: DUMMY VALUE
    internet:
      tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC
      discoveryDocumentUrl: https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-ref.app.ti-dienste.de
      xapiKey: DUMMY VALUE
      userAgent: DUMMY VALUE
    epaMockClient:
      epaMockUrl: https://epa-as-mock.ref.gematik.solutions:443
      epaMockApiKey: DUMMY VALUE
      logRetrieveInterval: 10000
      maxWait: 360000

  - name: RU-DEV
    ti:
      tslBaseUrl: http://download-ref.tsl.telematik-test/ECC
      discoveryDocumentUrl: https://idp-ref.zentral.idp.splitdns.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-dev.zentral.erp.splitdns.ti-dienste.de
      subscriptionServiceUrl: wss://subscription-dev.zentral.erp.splitdns.ti-dienste.de/subscription
      userAgent: DUMMY VALUE
    internet:
      tslBaseUrl: https://download-ref.tsl.ti-dienste.de/ECC
      discoveryDocumentUrl: https://idp-ref.app.ti-dienste.de/.well-known/openid-configuration
      fdBaseUrl: https://erp-dev.app.ti-dienste.de
      xapiKey: DUMMY VALUE
      userAgent: DUMMY VALUE
    epaMockClient:
      epaMockUrl: https://epa-as-mock.ref.gematik.solutions:443
      epaMockApiKey: DUMMY VALUE
      logRetrieveInterval: 10000
      maxWait: 360000
    tRegisterMockClient:
      tRegisterMockUrl: https://t-register.dev.gematik.solutions:443

konnektors:
  - name: "Soft-Konn"
    context:
      mandantId: "Mandant1"
      clientSystemId: "CS1"
      workplaceId: "AP1"
      userId: "user1"
    service:
      type: "Soft-Kon"
      vsdmConfiguration:
        hMacKey: "DUMMY VALUE"
        operator: S
        version: 1

  # --- Remote-Konnektoren ---
  - name: "KOCO@kon7"
    context:
      mandantId: "Mandant1"
      clientSystemId: "CS1"
      workplaceId: "AP1"
      userId: "user1"
    service:
      type: "Remote-Kon"
      address: "https://kon7.ksp.ltuzd.telematik-test"
      tls:
        keyStore: "tls/kon7_CS1.p12"
        keyStorePassword: "DUMMY VALUE"
        trustStore: "tls/erpe2e_truststore.p12"
        trustStorePassword: "DUMMY VALUE"
      basicAuth:
        username: "DUMMY VALUE"
        password: "DUMMY VALUE"
    cardTerminals:
      - type: "CATS"
        ctId: "CT_ID_0003"
        url: "https://ksp.ltuzd.telematik-test/kon7/cats1"
      - type: "CATS"
        ctId: "CT_ID_0004"
        url: "https://ksp.ltuzd.telematik-test/kon7/cats2"

  - name: "RISE@kon8"
    context:
      mandantId: "Mandant1"
      clientSystemId: "CS1"
      workplaceId: "AP1"
      userId: "user1"
    service:
      type: "Remote-Kon"
      address: "https://ksp.ltuzd.telematik-test/kon8"
      tls:
        keyStore: "tls/kon8_CS1.p12"
        keyStorePassword: "DUMMY VALUE"
        trustStore: "tls/erpe2e_truststore.p12"
        trustStorePassword: "DUMMY VALUE"
      basicAuth:
        username: "DUMMY VALUE"
        password: "DUMMY VALUE"
    cardTerminals:
      - type: "CATS"
        ctId: "02:42:0A:64:00:03"
        url: "https://ksp.ltuzd.telematik-test/kon8/cats"
      - type: "CATS"
        ctId: "02:42:0A:64:00:04"
        url: "https://ksp.ltuzd.telematik-test/kon8/cats2"

  - name: "SECUNET@kon9"
    context:
      mandantId: "Mandant1"
      clientSystemId: "CS1"
      workplaceId: "AP1"
      userId: "user1"
    service:
      type: "Remote-Kon"
      address: "https://kon9.ksp.ltuzd.telematik-test"
      tls:
        keyStore: "tls/kon9_CS1.p12"
        keyStorePassword: "DUMMY VALUE"
        trustStore: "tls/erpe2e_truststore.p12"
        trustStorePassword: "DUMMY VALUE"
      basicAuth:
        username: "DUMMY VALUE"
        password: "DUMMY VALUE"
    cardTerminals:
      - type: "CATS"
        ctId: "e526d874-e1fb-4b88-b55f-930a5ca7baab"
        url: "https://ksp.ltuzd.telematik-test/kon9/cats1"
      - type: "CATS"
        ctId: "8cf501d2-c97f-436e-8d87-ddd9bb674318"
        url: "https://ksp.ltuzd.telematik-test/kon9/cats2"

  - name: "RISE@hsk2"
    context:
      mandantId: "M1"
      clientSystemId: "C1"
      workplaceId: "W1"
      userId: "user1"
    service:
      type: "Remote-Kon"
      address: "https://kon2.rise-tu.hsk.ltuzd.telematik-test"
      tls:
        keyStore: "tls/hsk2_C1_ECC.p12"
        keyStorePassword: "DUMMY VALUE"
        trustStore: "tls/erpe2e_truststore.p12"
        trustStorePassword: "123456"
      basicAuth:
        username: "DUMMY VALUE"
        password: "DUMMY VALUE"
    cardTerminals:
      - type: "CATS"
        ctId: "02:42:0A:64:00:03"
        url: "https://rise-tu.hsk.ltuzd.telematik-test:443/kon2/cats"
      - type: "CATS"
        ctId: "02:42:0A:64:00:04"
        url: "https://rise-tu.hsk.ltuzd.telematik-test:443/kon2/cats2"
  - name: "SECUNET@HSK5"
    context:
      mandantId: "Mandant1"
      clientSystemId: "CS1"
      workplaceId: "AP1"
      userId: "user1"
    service:
      type: "Remote-Kon"
      address: "https://kon5.secunet-tu.hsk.ltuzd.telematik-test"
      tls:
        keyStore: "tls/secunet_hsk5_CS1.p12"
        keyStorePassword: "DUMMY VALUE"
        trustStore: "tls/erpe2e_truststore.p12"
        trustStorePassword: "DUMMY VALUE"
      basicAuth:
        username: "DUMMY VALUE"
        password: "DUMMY VALUE"
    cardTerminals:
      - type: "CATS"
        ctId: "6131b43c-bf0b-4706-82d9-b35b9827ac1d"
        url: "https://secunet-tu.hsk.ltuzd.telematik-test:443/kon5/cats"

poppTokenGenerator:
  keyStorePath: "popp/popp-token-Server2-nist-komp61.p12"
  keyStorePassword: "00"
  keyAlias: "alias"
  kid: "J3gf1Zvz281LpmRG0se2qzaJJA9aYRZ6DhAAHlZM6ok"
  iss: "https://popp.dev.poppservice.de"
