shouldLogCapabilityStatement: true

users:
  - name: Alice
    egkIccsn: 80276883110000115197
    useVirtualEgk: false
    device: T-Systems iPhone 14

apps:
  - platform: iOS
    appFile: cloud:uniqueName=20230509_1.13.0-18
    packageName: de.gematik.erp4ios.eRezept
  - platform: Android
    appFile: cloud:uniqueName=debug-tsystems0001
    espressoServerUniqueName: initialOchestratorTestAPK
    packageName: de.gematik.ti.erp.app.test

appium:
  - id: local
    url: http://0.0.0.0:4723
  - id: t-systems
    url: https://mobiledevicecloud.t-systems-mms.eu/wd/hub
    version: 2.0.0.beta.23
    maxWaitTimeout: 12000 # how many milliseconds to wait at maximum for an element
    pollingInterval: 100   # polling interval in milliseconds: (maxWaitTimeout/pollingInterval) = retries until NoSuchelementException

devices:
  - name: iPhone 14 Pro Max Simulator
    platform: iOS
    udid: CF5BE8A7-CBAE-4855-8E29-AFF4CFD45C6D
    platformVersion: 16.4
    appium: local

  - name: iPhone 7 Plus Simulator
    platform: iOS
    udid: F5209097-BA96-41CC-8D58-D225C9E9CFB9
    platformVersion: 16.4
    appium: local

