shouldLogCapabilityStatement: true

users:
  - name: Alice
    egkIccsn: 80276883110000163961
    useVirtualEgk: true
    device: T-Systems iPhone 14
  - name: Bob
    egkIccsn: 80276883110000163962
    useVirtualEgk: true # won't have any effects because Bob as co-user will always use virtual eGK

apps:
  - platform: iOS
    packageName: de.gematik.erp4ios.eRezept
  - platform: Android
    appFile: cloud:uniqueName=debug-tsystems0001
    espressoServerUniqueName: initialOchestratorTestAPK
    packageName: de.gematik.ti.erp.app.test

appium:
  - name: local
    url: http://0.0.0.0:4723
  - name: t-systems
    url: https://mobiledevicecloud.t-systems-mms.eu/wd/hub
    version: 2.11.3
    maxWaitTimeout: 12000 # how many milliseconds to wait at maximum for an element
    pollingInterval: 100   # polling interval in milliseconds: (maxWaitTimeout/pollingInterval) = retries until NoSuchelementException
    provisioningProfilePostfix: ".mdc2"
    accessKey: DUMMY VALUE
  - name: t-systems-public
    url: https://mobiledevicecloud.t-systems-mms.eu/wd/hub
    version: 2.11.3
    maxWaitTimeout: 12000
    pollingInterval: 100
    accessKey: DUMMY VALUE

devices:
  - name: iPhone 14 Pro Max Simulator
    platform: iOS
    udid: CF5BE8A7-CBAE-4855-8E29-AFF4CFD45C6D
    platformVersion: 16.4
    appium: local

  - name: iPhone 7 Plus Simulator
    platform: iOS
    udid: F5209097-BA96-41CC-8D58-D225C9E9CFB9
    platformVersion: 16.4
    appium: local

  - name: T-Systems iPhone 14 # gematik exclusive device with real eGK
    platform: iOS
    hasNfc: true
    udid: 00008110-000249802299401E
    platformVersion: 17.6.1
    appium: t-systems

  - name: T-Systems iPhone 12 Pro Max1  # public device only with virtual eGK
    platform: iOS
    udid: 00008101-000C50382103001E
    platformVersion: 17.3.1
    appium: t-systems-public
